<?php

/**
 * @file
 * Install, update and uninstall functions for my_profile install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */

function my_profile_install() {
  global $config_directories;

  $sync_directory = drupal_get_path('profile', 'my_profile') . '/config/sync';

  $file_storage = new \Drupal\Core\Config\FileStorage($sync_directory);
  
  // Match up the site uuid.
  $system_site = $file_storage->read('system.site');
  if (isset($system_site['uuid'])) {
    \Drupal::configFactory()
      ->getEditable('system.site')
      ->set('uuid', $system_site['uuid'])
      ->save();
  }

  // Update settings.php
  $settings['config_directories'][CONFIG_SYNC_DIRECTORY] = (object) [
    'value' => $sync_directory,
    'required' => TRUE,
  ];
  $config_directories[CONFIG_SYNC_DIRECTORY] = $sync_directory;
}